name: tracker
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      - ultralytics
      - boxmot
      - opencv-python>=4.8.0
      - numpy>=2.0.0
